apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-example
  name: prometheus-example
  namespace: monitoring-example-2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: web
  selector:
    app: prometheus-example
  type: ClusterIP
