---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-application-1
  namespace: argocd
spec:
  destination:
    namespace: monitoring-example-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring/examples/app1
    repoURL: https://github.com/tosmi/openshift-config-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-application-2
  namespace: argocd
spec:
  destination:
    namespace: monitoring-example-2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring/examples/app2
    repoURL: https://github.com/tosmi/openshift-config-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-monitoring-config
  namespace: argocd
spec:
  destination:
    namespace: openshift-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring/configuration
    repoURL: https://github.com/tosmi/openshift-config-argocd.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  destination:
    namespace: monitoring-example-1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: monitoring/grafana-operator
    repoURL: https://github.com/tosmi/openshift-config-argocd.git
