apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-storage
  namespace: argocd
spec:
  destination:
    namespace: openshift-storage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: storage/ocs
    repoURL: https://github.com/tosmi/openshift-config-argocd.git
