apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: blockpool
  namespace: rook-ceph
spec:
  failureDomain: host
  erasureCoded:
    dataChunks: 2
    codingChunks: 1
  deviceClass: hdd

